/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/web3.js';
import { VAULT_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const NEW_VAULT_TYPE_DISCRIMINATOR = new Uint8Array([
  115, 230, 146, 235, 63, 19, 186, 29,
]);

export function getNewVaultTypeDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    NEW_VAULT_TYPE_DISCRIMINATOR
  );
}

export type NewVaultTypeInstruction<
  TProgram extends string = typeof VAULT_PROGRAM_ADDRESS,
  TAccountVaultType extends string | IAccountMeta<string> = string,
  TAccountAuthority extends string | IAccountMeta<string> = string,
  TAccountMint extends string | IAccountMeta<string> = string,
  TAccountPool extends string | IAccountMeta<string> = string,
  TAccountPayer extends string | IAccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | IAccountMeta<string> = '11111111111111111111111111111111',
  TAccountTokenProgram extends
    | string
    | IAccountMeta<string> = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountVaultType extends string
        ? WritableAccount<TAccountVaultType>
        : TAccountVaultType,
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            IAccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountMint extends string
        ? ReadonlyAccount<TAccountMint>
        : TAccountMint,
      TAccountPool extends string
        ? ReadonlyAccount<TAccountPool>
        : TAccountPool,
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            IAccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type NewVaultTypeInstructionData = {
  discriminator: ReadonlyUint8Array;
  seasonStart: bigint;
  seasonDuration: bigint;
  cooldownWindow: bigint;
  maxDepositPerUser: bigint;
  instantDeactivation: boolean;
};

export type NewVaultTypeInstructionDataArgs = {
  seasonStart: number | bigint;
  seasonDuration: number | bigint;
  cooldownWindow: number | bigint;
  maxDepositPerUser: number | bigint;
  instantDeactivation: boolean;
};

export function getNewVaultTypeInstructionDataEncoder(): Encoder<NewVaultTypeInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['seasonStart', getI64Encoder()],
      ['seasonDuration', getI64Encoder()],
      ['cooldownWindow', getI64Encoder()],
      ['maxDepositPerUser', getU64Encoder()],
      ['instantDeactivation', getBooleanEncoder()],
    ]),
    (value) => ({ ...value, discriminator: NEW_VAULT_TYPE_DISCRIMINATOR })
  );
}

export function getNewVaultTypeInstructionDataDecoder(): Decoder<NewVaultTypeInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['seasonStart', getI64Decoder()],
    ['seasonDuration', getI64Decoder()],
    ['cooldownWindow', getI64Decoder()],
    ['maxDepositPerUser', getU64Decoder()],
    ['instantDeactivation', getBooleanDecoder()],
  ]);
}

export function getNewVaultTypeInstructionDataCodec(): Codec<
  NewVaultTypeInstructionDataArgs,
  NewVaultTypeInstructionData
> {
  return combineCodec(
    getNewVaultTypeInstructionDataEncoder(),
    getNewVaultTypeInstructionDataDecoder()
  );
}

export type NewVaultTypeAsyncInput<
  TAccountVaultType extends string = string,
  TAccountAuthority extends string = string,
  TAccountMint extends string = string,
  TAccountPool extends string = string,
  TAccountPayer extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  vaultType?: Address<TAccountVaultType>;
  authority: TransactionSigner<TAccountAuthority>;
  mint: Address<TAccountMint>;
  pool?: Address<TAccountPool>;
  payer: TransactionSigner<TAccountPayer>;
  systemProgram?: Address<TAccountSystemProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  seasonStart: NewVaultTypeInstructionDataArgs['seasonStart'];
  seasonDuration: NewVaultTypeInstructionDataArgs['seasonDuration'];
  cooldownWindow: NewVaultTypeInstructionDataArgs['cooldownWindow'];
  maxDepositPerUser: NewVaultTypeInstructionDataArgs['maxDepositPerUser'];
  instantDeactivation: NewVaultTypeInstructionDataArgs['instantDeactivation'];
};

export async function getNewVaultTypeInstructionAsync<
  TAccountVaultType extends string,
  TAccountAuthority extends string,
  TAccountMint extends string,
  TAccountPool extends string,
  TAccountPayer extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof VAULT_PROGRAM_ADDRESS,
>(
  input: NewVaultTypeAsyncInput<
    TAccountVaultType,
    TAccountAuthority,
    TAccountMint,
    TAccountPool,
    TAccountPayer,
    TAccountSystemProgram,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  NewVaultTypeInstruction<
    TProgramAddress,
    TAccountVaultType,
    TAccountAuthority,
    TAccountMint,
    TAccountPool,
    TAccountPayer,
    TAccountSystemProgram,
    TAccountTokenProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? VAULT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    vaultType: { value: input.vaultType ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: false },
    mint: { value: input.mint ?? null, isWritable: false },
    pool: { value: input.pool ?? null, isWritable: false },
    payer: { value: input.payer ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.vaultType.value) {
    accounts.vaultType.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([118, 97, 117, 108, 116, 95, 116, 121, 112, 101])
        ),
        getAddressEncoder().encode(expectAddress(accounts.mint.value)),
        getAddressEncoder().encode(expectAddress(accounts.authority.value)),
      ],
    });
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }
  if (!accounts.pool.value) {
    accounts.pool.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getAddressEncoder().encode(expectAddress(accounts.vaultType.value)),
        getAddressEncoder().encode(expectAddress(accounts.tokenProgram.value)),
        getAddressEncoder().encode(expectAddress(accounts.mint.value)),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.vaultType),
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.pool),
      getAccountMeta(accounts.payer),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.tokenProgram),
    ],
    programAddress,
    data: getNewVaultTypeInstructionDataEncoder().encode(
      args as NewVaultTypeInstructionDataArgs
    ),
  } as NewVaultTypeInstruction<
    TProgramAddress,
    TAccountVaultType,
    TAccountAuthority,
    TAccountMint,
    TAccountPool,
    TAccountPayer,
    TAccountSystemProgram,
    TAccountTokenProgram
  >;

  return instruction;
}

export type NewVaultTypeInput<
  TAccountVaultType extends string = string,
  TAccountAuthority extends string = string,
  TAccountMint extends string = string,
  TAccountPool extends string = string,
  TAccountPayer extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  vaultType: Address<TAccountVaultType>;
  authority: TransactionSigner<TAccountAuthority>;
  mint: Address<TAccountMint>;
  pool: Address<TAccountPool>;
  payer: TransactionSigner<TAccountPayer>;
  systemProgram?: Address<TAccountSystemProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  seasonStart: NewVaultTypeInstructionDataArgs['seasonStart'];
  seasonDuration: NewVaultTypeInstructionDataArgs['seasonDuration'];
  cooldownWindow: NewVaultTypeInstructionDataArgs['cooldownWindow'];
  maxDepositPerUser: NewVaultTypeInstructionDataArgs['maxDepositPerUser'];
  instantDeactivation: NewVaultTypeInstructionDataArgs['instantDeactivation'];
};

export function getNewVaultTypeInstruction<
  TAccountVaultType extends string,
  TAccountAuthority extends string,
  TAccountMint extends string,
  TAccountPool extends string,
  TAccountPayer extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof VAULT_PROGRAM_ADDRESS,
>(
  input: NewVaultTypeInput<
    TAccountVaultType,
    TAccountAuthority,
    TAccountMint,
    TAccountPool,
    TAccountPayer,
    TAccountSystemProgram,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress }
): NewVaultTypeInstruction<
  TProgramAddress,
  TAccountVaultType,
  TAccountAuthority,
  TAccountMint,
  TAccountPool,
  TAccountPayer,
  TAccountSystemProgram,
  TAccountTokenProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? VAULT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    vaultType: { value: input.vaultType ?? null, isWritable: true },
    authority: { value: input.authority ?? null, isWritable: false },
    mint: { value: input.mint ?? null, isWritable: false },
    pool: { value: input.pool ?? null, isWritable: false },
    payer: { value: input.payer ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.vaultType),
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.pool),
      getAccountMeta(accounts.payer),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.tokenProgram),
    ],
    programAddress,
    data: getNewVaultTypeInstructionDataEncoder().encode(
      args as NewVaultTypeInstructionDataArgs
    ),
  } as NewVaultTypeInstruction<
    TProgramAddress,
    TAccountVaultType,
    TAccountAuthority,
    TAccountMint,
    TAccountPool,
    TAccountPayer,
    TAccountSystemProgram,
    TAccountTokenProgram
  >;

  return instruction;
}

export type ParsedNewVaultTypeInstruction<
  TProgram extends string = typeof VAULT_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    vaultType: TAccountMetas[0];
    authority: TAccountMetas[1];
    mint: TAccountMetas[2];
    pool: TAccountMetas[3];
    payer: TAccountMetas[4];
    systemProgram: TAccountMetas[5];
    tokenProgram: TAccountMetas[6];
  };
  data: NewVaultTypeInstructionData;
};

export function parseNewVaultTypeInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedNewVaultTypeInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      vaultType: getNextAccount(),
      authority: getNextAccount(),
      mint: getNextAccount(),
      pool: getNextAccount(),
      payer: getNextAccount(),
      systemProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getNewVaultTypeInstructionDataDecoder().decode(instruction.data),
  };
}
