/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/web3.js';
import { VAULT_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const TRANSFER_FROM_POOL_DISCRIMINATOR = new Uint8Array([
  136, 167, 45, 66, 74, 252, 0, 16,
]);

export function getTransferFromPoolDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    TRANSFER_FROM_POOL_DISCRIMINATOR
  );
}

export type TransferFromPoolInstruction<
  TProgram extends string = typeof VAULT_PROGRAM_ADDRESS,
  TAccountVaultType extends string | IAccountMeta<string> = string,
  TAccountAuthority extends string | IAccountMeta<string> = string,
  TAccountMint extends string | IAccountMeta<string> = string,
  TAccountPool extends string | IAccountMeta<string> = string,
  TAccountDestination extends string | IAccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | IAccountMeta<string> = '11111111111111111111111111111111',
  TAccountTokenProgram extends
    | string
    | IAccountMeta<string> = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountVaultType extends string
        ? ReadonlyAccount<TAccountVaultType>
        : TAccountVaultType,
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            IAccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountMint extends string
        ? ReadonlyAccount<TAccountMint>
        : TAccountMint,
      TAccountPool extends string
        ? WritableAccount<TAccountPool>
        : TAccountPool,
      TAccountDestination extends string
        ? WritableAccount<TAccountDestination>
        : TAccountDestination,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type TransferFromPoolInstructionData = {
  discriminator: ReadonlyUint8Array;
  amount: bigint;
};

export type TransferFromPoolInstructionDataArgs = { amount: number | bigint };

export function getTransferFromPoolInstructionDataEncoder(): Encoder<TransferFromPoolInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['amount', getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: TRANSFER_FROM_POOL_DISCRIMINATOR })
  );
}

export function getTransferFromPoolInstructionDataDecoder(): Decoder<TransferFromPoolInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['amount', getU64Decoder()],
  ]);
}

export function getTransferFromPoolInstructionDataCodec(): Codec<
  TransferFromPoolInstructionDataArgs,
  TransferFromPoolInstructionData
> {
  return combineCodec(
    getTransferFromPoolInstructionDataEncoder(),
    getTransferFromPoolInstructionDataDecoder()
  );
}

export type TransferFromPoolAsyncInput<
  TAccountVaultType extends string = string,
  TAccountAuthority extends string = string,
  TAccountMint extends string = string,
  TAccountPool extends string = string,
  TAccountDestination extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  vaultType?: Address<TAccountVaultType>;
  authority: TransactionSigner<TAccountAuthority>;
  mint: Address<TAccountMint>;
  pool?: Address<TAccountPool>;
  destination: Address<TAccountDestination>;
  systemProgram?: Address<TAccountSystemProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  amount: TransferFromPoolInstructionDataArgs['amount'];
};

export async function getTransferFromPoolInstructionAsync<
  TAccountVaultType extends string,
  TAccountAuthority extends string,
  TAccountMint extends string,
  TAccountPool extends string,
  TAccountDestination extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof VAULT_PROGRAM_ADDRESS,
>(
  input: TransferFromPoolAsyncInput<
    TAccountVaultType,
    TAccountAuthority,
    TAccountMint,
    TAccountPool,
    TAccountDestination,
    TAccountSystemProgram,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  TransferFromPoolInstruction<
    TProgramAddress,
    TAccountVaultType,
    TAccountAuthority,
    TAccountMint,
    TAccountPool,
    TAccountDestination,
    TAccountSystemProgram,
    TAccountTokenProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? VAULT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    vaultType: { value: input.vaultType ?? null, isWritable: false },
    authority: { value: input.authority ?? null, isWritable: false },
    mint: { value: input.mint ?? null, isWritable: false },
    pool: { value: input.pool ?? null, isWritable: true },
    destination: { value: input.destination ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.vaultType.value) {
    accounts.vaultType.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([118, 97, 117, 108, 116, 95, 116, 121, 112, 101])
        ),
        getAddressEncoder().encode(expectAddress(accounts.mint.value)),
        getAddressEncoder().encode(expectAddress(accounts.authority.value)),
      ],
    });
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }
  if (!accounts.pool.value) {
    accounts.pool.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getAddressEncoder().encode(expectAddress(accounts.vaultType.value)),
        getAddressEncoder().encode(expectAddress(accounts.tokenProgram.value)),
        getAddressEncoder().encode(expectAddress(accounts.mint.value)),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.vaultType),
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.pool),
      getAccountMeta(accounts.destination),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.tokenProgram),
    ],
    programAddress,
    data: getTransferFromPoolInstructionDataEncoder().encode(
      args as TransferFromPoolInstructionDataArgs
    ),
  } as TransferFromPoolInstruction<
    TProgramAddress,
    TAccountVaultType,
    TAccountAuthority,
    TAccountMint,
    TAccountPool,
    TAccountDestination,
    TAccountSystemProgram,
    TAccountTokenProgram
  >;

  return instruction;
}

export type TransferFromPoolInput<
  TAccountVaultType extends string = string,
  TAccountAuthority extends string = string,
  TAccountMint extends string = string,
  TAccountPool extends string = string,
  TAccountDestination extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  vaultType: Address<TAccountVaultType>;
  authority: TransactionSigner<TAccountAuthority>;
  mint: Address<TAccountMint>;
  pool: Address<TAccountPool>;
  destination: Address<TAccountDestination>;
  systemProgram?: Address<TAccountSystemProgram>;
  tokenProgram?: Address<TAccountTokenProgram>;
  amount: TransferFromPoolInstructionDataArgs['amount'];
};

export function getTransferFromPoolInstruction<
  TAccountVaultType extends string,
  TAccountAuthority extends string,
  TAccountMint extends string,
  TAccountPool extends string,
  TAccountDestination extends string,
  TAccountSystemProgram extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof VAULT_PROGRAM_ADDRESS,
>(
  input: TransferFromPoolInput<
    TAccountVaultType,
    TAccountAuthority,
    TAccountMint,
    TAccountPool,
    TAccountDestination,
    TAccountSystemProgram,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress }
): TransferFromPoolInstruction<
  TProgramAddress,
  TAccountVaultType,
  TAccountAuthority,
  TAccountMint,
  TAccountPool,
  TAccountDestination,
  TAccountSystemProgram,
  TAccountTokenProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? VAULT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    vaultType: { value: input.vaultType ?? null, isWritable: false },
    authority: { value: input.authority ?? null, isWritable: false },
    mint: { value: input.mint ?? null, isWritable: false },
    pool: { value: input.pool ?? null, isWritable: true },
    destination: { value: input.destination ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.vaultType),
      getAccountMeta(accounts.authority),
      getAccountMeta(accounts.mint),
      getAccountMeta(accounts.pool),
      getAccountMeta(accounts.destination),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.tokenProgram),
    ],
    programAddress,
    data: getTransferFromPoolInstructionDataEncoder().encode(
      args as TransferFromPoolInstructionDataArgs
    ),
  } as TransferFromPoolInstruction<
    TProgramAddress,
    TAccountVaultType,
    TAccountAuthority,
    TAccountMint,
    TAccountPool,
    TAccountDestination,
    TAccountSystemProgram,
    TAccountTokenProgram
  >;

  return instruction;
}

export type ParsedTransferFromPoolInstruction<
  TProgram extends string = typeof VAULT_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    vaultType: TAccountMetas[0];
    authority: TAccountMetas[1];
    mint: TAccountMetas[2];
    pool: TAccountMetas[3];
    destination: TAccountMetas[4];
    systemProgram: TAccountMetas[5];
    tokenProgram: TAccountMetas[6];
  };
  data: TransferFromPoolInstructionData;
};

export function parseTransferFromPoolInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedTransferFromPoolInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      vaultType: getNextAccount(),
      authority: getNextAccount(),
      mint: getNextAccount(),
      pool: getNextAccount(),
      destination: getNextAccount(),
      systemProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getTransferFromPoolInstructionDataDecoder().decode(instruction.data),
  };
}
